version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - url-shortener-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  mongo-data: 